### ISSUE TITLE
NoMethodError

### ISSUE THREAD

**Issue by daffydowden** [arsduo/oauth_playground#1]
Hi arsduo,

I cloned this sample in order to play around with your koala gem, but after setting it up I'm getting an error upon signing in and authenticating with Facebook. I'm getting a NoMethodError - undefined method 'each_pair' on line 176 of index.erb. On the brief bit of debugging I did it would appear that the incorrect cookie is being passed. Could you tell me whether you are seeing this error too?

Daf

**Comment by arsduo** [comment]
Hey Daf,

Thanks for reporting that!  I forgot to update that section when a method changed.  If you check out the current version, it should work for you.

(Note: the live site is down currently, should be up again soon.)

Alex

**Comment by daffydowden** [comment]
Cheers Alex, works perfectly now.
